### ISSUE TITLE
What does dx mean in run(dx), hop(dx), and leap(dx)

### ISSUE THREAD

**Issue by Ynjxsjmh** [WarwickMasson/aaai-platformer#1]
In your paper [Reinforcement Learning with Parameterized Actions](https://arxiv.org/pdf/1509.01644.pdf), you introduce this new environment platform.

![image](https://user-images.githubusercontent.com/40143136/140653743-d947df40-d5ed-4608-8794-129dc633034c.png)

I try to search around the paper and find you only use `dx` in this three actions but never denote them. Would you mind tell what does they mean?

**Comment by WarwickMasson** [comment]
Hi, each of the parameterized actions  run, hop, and leap take a parameter `dx` which essentially determines how much force or strength to use with the action.

**Comment by Ynjxsjmh** [comment]
Thank you, the meaning of dx argument is well represented in your [simulator.py](https://github.com/WarwickMasson/aaai-platformer/blob/0d2501973db1d99d83dc839649e245faa0c930d2/simulator.py#L232).
